CREATE COLUMN TABLE CUST_TICKETS (
    "ID" NVARCHAR(36) NOT NULL,  -- UUID or unique ID
    "PROCESSOR" NVARCHAR(100),
    "PROCESSDATE" DATE,
    "PROCESSTIME" TIME,
    "REPORTEDBY" NVARCHAR(100),
    "DECISION" NVARCHAR(50),
    "REDDITPOSTID" NVARCHAR(50),
    "MAINTENANCENOTIFICATIONID" NVARCHAR(50),
    "LAT" DECIMAL(10,6),
    "LONG" DECIMAL(10,6),               -- Large string storage
    "GENAISUMMARY" NCLOB,       -- Large string storage
    "GENAIDESCRIPTION" NCLOB,   -- Large string storage
    "PRIORITY" NVARCHAR(10),
    "PRIORITYDESC" NVARCHAR(100),
    "SENTIMENT" NVARCHAR(50),
    "CATEGORY" NVARCHAR(50),
    "DATE" DATE,
    "TIME" TIME,
    PRIMARY KEY ("ID")
);

SELECT TO_VARCHAR(SYSUUID) AS UUID FROM DUMMY;

SELECT current_schema AS UUID FROM DUMMY;